_BASE_: "Base-CFPN.yaml"
MODEL:
  DEVICE: 'cuda:0'
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 128
  RECONSTRUCT_HEADS_ON: True
  RECONSTRUCT_HEADS:
    LOSS_WEIGHTS: [1, 0.5, 0.33333, 0.25]
    NAME: "MLResidualHead"
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    IN_CHANNELS: 128
SOLVER:
  BASE_LR: 0.0002
INPUT:
  FORMAT: "BGR"


