_BASE_: "Base-CFPN.yaml"
MODEL:
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 128
  RECONSTRUCT_HEADS_ON: True
  RECONSTRUCT_HEADS:
    NAME: "MLSPHead"
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    IN_CHANNELS: 128
    OUTPUT_IMAGES: ['img_2', 'img_3', 'img_4', 'img_5', 'img_6']
SOLVER:
  BASE_LR: 0.0000002
VIS_PERIOD: 100
INPUT:
  FORMAT: "BGR"

