MODEL:
  DEVICE: 'cuda:0'
  META_ARCHITECTURE: "CFPN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  BACKBONE:
    NAME: "QFPN"
    FREEZE_AT: 1
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
  DETECTION_ON: True
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 2000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  QUANTIZER_ON: True
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
#    OUT_CHANNELS: 512
  RECONSTRUCT_HEADS_ON: False
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  NUM_WORKERS: 10
SOLVER:
  IMS_PER_BATCH: 4 #base 16
  BASE_LR: 0.02
  STEPS: (240000, 320000) #base (60000, 80000)
  MAX_ITER: 360000 #base 90000
TEST:
  EVAL_PERIOD: 3000
VIS_PERIOD: 200
INPUT:
   FORMAT: "BGR"
   MIN_SIZE_TRAIN: (512,)
   MAX_SIZE_TRAIN: 512
   MIN_SIZE_TRAIN_SAMPLING: 'choice'
   MIN_SIZE_TEST: 512
   MAX_SIZE_TEST: 512
#INPUT:
#  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2


#MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  MASK_ON: False
#  META_ARCHITECTURE: "GeneralizedRCNN"
#  BACKBONE:
#    NAME: "build_resnet_fpn_backbone"
#  RESNETS:
#    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
#    DEPTH: 50
#  FPN:
#    IN_FEATURES: ["res2", "res3", "res4", "res5"]
#  ANCHOR_GENERATOR:
#    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
#    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
#  RPN:
#    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
#    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
#    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
#    # Detectron1 uses 2000 proposals per-batch,
#    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
#    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
#    POST_NMS_TOPK_TRAIN: 1000
#    POST_NMS_TOPK_TEST: 1000
#  ROI_HEADS:
#    NAME: "StandardROIHeads"
#    IN_FEATURES: ["p2", "p3", "p4", "p5"]
#  ROI_BOX_HEAD:
#    NAME: "FastRCNNConvFCHead"
#    NUM_FC: 2
#    POOLER_RESOLUTION: 7
#  ROI_MASK_HEAD:
#    NAME: "MaskRCNNConvUpsampleHead"
#    NUM_CONV: 4
#    POOLER_RESOLUTION: 14
#DATASETS:
#  TRAIN: ("coco_2017_train",)
#  TEST: ("coco_2017_val",)
#SOLVER:
#  IMS_PER_BATCH: 2 #base 8
#  BASE_LR: 0.02
#  STEPS: (120000, 160000) #base (60000, 80000)
#  MAX_ITER: 180000 #base 90000
#INPUT:
#  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
#TEST: #not in original
#  EVAL_PERIOD: 8000
#VIS_PERIOD: 1000 # not in original
#VERSION: 2
