_BASE_: "Base-Quantized-CFPN.yaml"
MODEL:
  DEVICE: 'cuda:0'
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 512
  RECONSTRUCT_HEADS_ON: True
  RECONSTRUCT_HEADS:
    NAME: "MLSPHead"
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    IN_CHANNELS: 512
    OUTPUT_IMAGES: ['img_2', 'img_3', 'img_4', 'img_5', 'img_6']
SOLVER:
  BASE_LR: 0.00002
INPUT:
  FORMAT: "BGR"


