_BASE_: "Base-Quantized-CFPN.yaml"
MODEL:
  QUANTIZER_ON: True
  DEVICE: 'cpu'
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
  RECONSTRUCT_HEADS_ON: False
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.0002
DATASETS:
  TRAIN: ("voc_2012_trainval",)
  TEST: ("kodak_test",)
INPUT:
  FORMAT: "BGR"
TEST:
  EVAL_PERIOD: 1
  NUM_COMPRESSION_IMAGES: 10

